# Generated by Django 5.2.5 on 2025-08-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(default='10 min', max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
